/**
 * KÖLN ESSENMEILE – Blog API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Einheitliches Fehlerobjekt.
 */
export interface ApiError { 
    /**
     * Menschable Fehlermeldung (Deutsch).
     */
    error: string;
}

