/**
 * KÖLN ESSENMEILE – Blog API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Felder zum Anlegen/Ändern eines Posts (JSON-Body). 
 */
export interface PostRequest { 
    /**
     * Pflichtfeld, darf nicht leer sein.
     */
    title: string;
    description?: string;
    content?: string;
    /**
     * Optionales Titelbild als Data-URL mit Base64-Inhalt (z. B. `data:image/png;base64,iVBORw0K...`). Erlaubte Formate: jpg, jpeg, png, gif, webp. Maximal 5 MB (dekodiert). 
     */
    image?: string;
}

