/**
 * KÖLN ESSENMEILE – Blog API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ein Post, wie ihn die API zurückgibt.
 */
export interface PostResponse { 
    id: number;
    title: string;
    description: string;
    content: string;
    /**
     * Erstellzeitpunkt als lokale Zeit ohne Zeitzonen-Offset (z. B. `2026-06-13T13:45:18`). Kann Sekundenbruchteile enthalten. 
     */
    createdAt: string;
    /**
     * Zeitpunkt der letzten Änderung (gleiche Form wie createdAt).
     */
    updatedAt: string;
    /**
     * Relativer Pfad zum Titelbild (z. B. `uploads/xyz.jpg`) oder `null`, wenn kein Bild vorhanden ist. Für die volle URL die Server-Basis davorsetzen. 
     */
    coverImage: string | null;
}

